[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "20"
PLAYWRIGHT_BROWSERS_PATH = "0"

[[redirects]]
from = "/"
to = "https://hadronomy.com"

[[redirects]]
from = "/2024/bolt/pdf"
to = "https://github.com/hadronomy/talks/blob/main/2024-11-16/2024-12-16-bolt-es.pdf?raw=true"
