packages:
  - '*/src'
catalog:
  '@antfu/eslint-config': ^4.1.0
  '@eslint/config-inspector': ^1.0.0
  '@iconify/collections': ^1.0.512
  '@iconify/json': ^2.2.301
  '@slidev/cli': ^51.1.0
  '@slidev/client': ^51.1.0
  '@slidev/theme-default': ^0.25.0
  '@types/node': ^22.13.0
  '@types/prompts': ^2.4.9
  '@types/seedrandom': ^3.0.8
  chroma-js: ^3.1.2
  eslint: ^9.19.0
  eslint-plugin-format: ^1.0.1
  esno: ^4.8.0
  execa: ^9.5.2
  fast-glob: ^3.3.3
  markdown-it-magic-link: ^0.1.4
  playwright-chromium: ^1.50.1
  pnpm: ^9.15.4
  prettier-plugin-slidev: ^1.0.5
  prompts: ^2.4.2
  rimraf: ^6.0.1
  seedrandom: ^3.0.5
  slidev-addon-graph: ^0.1.0
  taze: ^18.3.0
  typescript: ^5.7.3
  unocss: ^65.4.3
  vis-data: ^7.1.9
  vis-network: ^9.1.9
  vis-timeline: ^7.7.3
  vue-router: ^4.5.0
  vue-tsc: ^2.2.0
